require("diffview").setup()
local repo = require("bitbucket.repo")
local requests = require("bitbucket.requests")
local tree = require("bitbucket.comments.tree")
local utils = require("bitbucket.utils")
describe("helper functions", function()
	it("handle_request_new_comment", function()
		bufnr = utils.create_vertial_split()
		vim.api.nvim_buf_set_lines(bufnr, -1, -1, true, { "abc", "def" })
		repo.pr_id = 1
		local values, status = requests.request_comments_table(1)
		tree.comments_view(values)
		local node_id = requests.handle_request_new_comment(bufnr, nil)
		requests.delete_comment(node_id)
	end)
end)
